org: subash1999
app: ride-sharing-app
service: driver-serverice

useDotenv: true # Enable dotenv plugin to load environment variables from .env file

provider:
  name: aws
  runtime: nodejs20.x
  stage: ${opt:stage, 'development'} # Default stage is 'development'
  region: us-east-1
  environment:
    NODE_ENV: ${env:NODE_ENV, 'development'} # Reference the environment variable from .env file
    SERVERLESS_ACCESS_KEY: AK31C6gtUVB7De2HmcBCTDOYwVY5nXoHNIeyx2xjVnDvh

functions:
  api:
    handler: handler.handler
    events:
      - httpApi:
          path: "/{proxy+}"
          method: any

plugins:
  - serverless-localstack # Plugin to integrate with LocalStack
  - serverless-offline # Optional: Allows offline API testing
  - serverless-webpack-offline-reload

custom:
  dotenv:
    path: ./env/.env.${self:provider.stage} # Load .env file based on the stage (from env/ folder)
  localstack:
    debug: true
    stages:
      - development
    endpointFile: config/localstack-endpoints.json # Optional: Define custom endpoints
    host: http://localstack:4566 # LocalStack container name in Docker Compose

resources:
  Resources:
    ApiGateway:
      Type: AWS::ApiGateway::RestApi
      Properties:
        Name: driver-serverless-api
